[package]
title = "Undo/Redo Commands System"
category = "Internal"
reloadable = false
version = "1.4.5"
changelog="docs/CHANGELOG.md"

[dependencies]
"omni.kit.actions.core" = {}

[[python.module]]
name = "omni.kit.undo"

[[python.module]]
name = "omni.kit.commands"

# Bring in some builtin commands
[[python.module]]
name = "omni.kit.commands.builtin"

[settings]
# Store last N command history entries in crash report
exts."omni.kit.commands".crashReportHistoryCount = 10

[[native.plugin]]
path = "bin/*.plugin"
